= Reader for fortune files

Implementation of a reader for fortune files in PHP.

== Usage

.Retrieve random fortune
[,php]
----
use vitoni\Fortunes;

$fortunes = Fortunes::from($path);

echo $fortunes->getRandom();
----

.Use Fortunes as (read-only) array
[,php]
----
use vitoni\Fortunes;

$fortunes = Fortunes::from($path);

$randOffset = $fortunes->getRandomOffset();

echo $fortunes[$randOffset];
----

.Access using an Iterator
[,php]
----
use vitoni\Fortunes;

$fortunes = Fortunes::read($path);

foreach ($fortunes as $fortune) {
    ...
}
----

== Over-engineered example

Re-reading the fortune file / directory to find all fortunes on each call might be not the best idea.
In case of a MOTD this might work but for a web page this approach might not fit.

One can use the `indexer` example to create a static index of all fortunes.
This index can be used as long as the files don't change (it could be used even then when one only appends to existing files with the downside of missing out on new fortunes).

.Outputs a ready to use PHP script with Fortunes set up with a static index
[,shell]
----
php examples/indexer.php tests/_files
----

.Static reader demo
[,shell]
----
php examples/indexer.php tests/_files \
  | cat - <(echo 'echo $fortunes->getRandom() . "\\n";') \
  | php
----

What the snippet does:

* Creates a static index and prepares a Fortunes instance
* Uses output from `indexer` and appends `echo $fortunes->getRandom() . "\n";`
* Pipes everything to `php` to execute the created script to retrieve a random fortune

.Output
[,txt]
----
This is fortune 4
----

=== Other approaches

One could created a static PHP readable version with the fortunes included, or something totally different. +
But where would the fun be?

The https://cgit.freebsd.org/src/tree/usr.bin/fortune/fortune[original fortunes] uses `.dat` files which do basically the same but have a per file index.

== Development

This project uses https://getcomposer.org/[composer] for dependency management.

.Install dependencies and create autoloader script
[,shell]
----
composer install
----

.Execute tests (indirectly with `composer`)
[,shell]
----
composer run-script test
----

.Execute tests (directly with `phpunit`)
[,shell]
----
./vendor/bin/phpunit
----

== References

=== Implementations

* C
** https://cgit.freebsd.org/src/tree/usr.bin/fortune/fortune[fortune - FreeBSD]
** https://github.com/freebsd/freebsd-src/tree/main/usr.bin/fortune/fortune[fortune - FreeBSD - GitHub]
** https://github.com/shlomif/fortune-mod[fortune-mod - Maintenance Version and Ongoing Development]
* PHP
** https://pear.php.net/package/File_Fortune/[File_Fortune] - by https://github.com/weierophinney[weierophinney]
* Python
** https://github.com/HubTou/fortune[fortune - by HubTou]
* and many more...

=== Cookies

* http://fortunes.cat-v.org/[Jar of Fortune Files]
* https://github.com/koitsu/fortune-mod-freebsd-classic/[Classic FreeBSD fortunes (incl. offensives)]
* https://github.com/HubTou/fortunes-freebsd-classic[Classical FreeBSD fortune data files]
* https://github.com/HubTou/fortunes-historical[Historical fortune data files]
* https://github.com/JKirchartz/fortunes[Personal collection of Fortune files of JKirchartz]
* https://github.com/alberanid/fortunes-spam[Fortune cookies taken from subjects and bodies of funny or strange SPAM messages]
* ...

=== Other

* https://en.wikipedia.org/wiki/Fortune_(Unix)[fortune - Wikipedia]
